
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class AttributeTemplates
{
    private readonly System.Collections.Generic.Dictionary<int, DRAttributeTemplates> _dataMap;
    private readonly System.Collections.Generic.List<DRAttributeTemplates> _dataList;
    
    public AttributeTemplates(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DRAttributeTemplates>(_buf.Count);
        _dataList = new System.Collections.Generic.List<DRAttributeTemplates>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            DRAttributeTemplates _v;
            _v = global::cfg.DRAttributeTemplates.DeserializeDRAttributeTemplates(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Code, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, DRAttributeTemplates> DataMap => _dataMap;
    public System.Collections.Generic.List<DRAttributeTemplates> DataList => _dataList;

    public DRAttributeTemplates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRAttributeTemplates Get(int key) => _dataMap[key];
    public DRAttributeTemplates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

