
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class Buffs
{
    private readonly System.Collections.Generic.Dictionary<int, DRBuff> _dataMap;
    private readonly System.Collections.Generic.List<DRBuff> _dataList;
    
    public Buffs(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DRBuff>(_buf.Count);
        _dataList = new System.Collections.Generic.List<DRBuff>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            DRBuff _v;
            _v = global::cfg.DRBuff.DeserializeDRBuff(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, DRBuff> DataMap => _dataMap;
    public System.Collections.Generic.List<DRBuff> DataList => _dataList;

    public DRBuff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRBuff Get(int key) => _dataMap[key];
    public DRBuff this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

