
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class Characters
{
    private readonly System.Collections.Generic.Dictionary<int, DRCharacters> _dataMap;
    private readonly System.Collections.Generic.List<DRCharacters> _dataList;
    
    public Characters(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DRCharacters>(_buf.Count);
        _dataList = new System.Collections.Generic.List<DRCharacters>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            DRCharacters _v;
            _v = global::cfg.DRCharacters.DeserializeDRCharacters(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Code, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, DRCharacters> DataMap => _dataMap;
    public System.Collections.Generic.List<DRCharacters> DataList => _dataList;

    public DRCharacters GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRCharacters Get(int key) => _dataMap[key];
    public DRCharacters this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

