
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class DRAttributeTemplates : Luban.BeanBase
{
    public DRAttributeTemplates(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Code = (int)_obj.GetValue("Code");
        Name = (string)_obj.GetValue("Name");
        UpgradeCode = (int)_obj.GetValue("UpgradeCode");
        { var __json0 = _obj.GetValue("ActiveSkills"); ActiveSkills = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  ActiveSkills.Add(__v0); }   }
        { var __json0 = _obj.GetValue("PassiveSkills"); PassiveSkills = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  PassiveSkills.Add(__v0); }   }
        Hp = (int)_obj.GetValue("Hp");
        MaxHp = (int)_obj.GetValue("MaxHp");
        ExtraHp = (int)_obj.GetValue("ExtraHp");
        PhysicsAttack = (int)_obj.GetValue("PhysicsAttack");
        MagicAttack = (int)_obj.GetValue("MagicAttack");
        ExtraPhysicsAttack = (int)_obj.GetValue("ExtraPhysicsAttack");
        ExtraMagicAttack = (int)_obj.GetValue("ExtraMagicAttack");
        PhysicsDefense = (int)_obj.GetValue("PhysicsDefense");
        MagicDefense = (int)_obj.GetValue("MagicDefense");
        Mana = (int)_obj.GetValue("Mana");
        MaxMana = (int)_obj.GetValue("MaxMana");
        CriticalR = (int)_obj.GetValue("CriticalR");
        AttackSpeedR = (int)_obj.GetValue("AttackSpeedR");
        CooldownReduceR = (int)_obj.GetValue("CooldownReduceR");
        PhysicsPenetrationR = (int)_obj.GetValue("PhysicsPenetrationR");
        MagicPenetrationR = (int)_obj.GetValue("MagicPenetrationR");
        MoveSpeed = (int)_obj.GetValue("MoveSpeed");
        PhysicsBloodsuckingR = (int)_obj.GetValue("PhysicsBloodsuckingR");
        MagicBloodsuckingR = (int)_obj.GetValue("MagicBloodsuckingR");
        AttackRange = (int)_obj.GetValue("AttackRange");
        PerSecondBloodR = (int)_obj.GetValue("PerSecondBloodR");
        PerSecondManaR = (int)_obj.GetValue("PerSecondManaR");
        ResilienceR = (int)_obj.GetValue("ResilienceR");
    }

    public static DRAttributeTemplates DeserializeDRAttributeTemplates(JToken _buf)
    {
        return new DRAttributeTemplates(_buf);
    }

    /// <summary>
    /// 角色编号
    /// </summary>
    public readonly int Code;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 升级战斗属性方案
    /// </summary>
    public readonly int UpgradeCode;
    /// <summary>
    /// 主动技能
    /// </summary>
    public readonly System.Collections.Generic.List<int> ActiveSkills;
    /// <summary>
    /// 被动技能
    /// </summary>
    public readonly System.Collections.Generic.List<int> PassiveSkills;
    /// <summary>
    /// 属性1
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 属性2
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 属性3
    /// </summary>
    public readonly int ExtraHp;
    /// <summary>
    /// 属性4
    /// </summary>
    public readonly int PhysicsAttack;
    /// <summary>
    /// 属性5
    /// </summary>
    public readonly int MagicAttack;
    /// <summary>
    /// 属性6
    /// </summary>
    public readonly int ExtraPhysicsAttack;
    /// <summary>
    /// 属性7
    /// </summary>
    public readonly int ExtraMagicAttack;
    /// <summary>
    /// 属性8
    /// </summary>
    public readonly int PhysicsDefense;
    /// <summary>
    /// 属性9
    /// </summary>
    public readonly int MagicDefense;
    /// <summary>
    /// 属性10
    /// </summary>
    public readonly int Mana;
    /// <summary>
    /// 属性11
    /// </summary>
    public readonly int MaxMana;
    /// <summary>
    /// 属性12
    /// </summary>
    public readonly int CriticalR;
    /// <summary>
    /// 属性13
    /// </summary>
    public readonly int AttackSpeedR;
    /// <summary>
    /// 属性14
    /// </summary>
    public readonly int CooldownReduceR;
    /// <summary>
    /// 属性15
    /// </summary>
    public readonly int PhysicsPenetrationR;
    /// <summary>
    /// 属性16
    /// </summary>
    public readonly int MagicPenetrationR;
    /// <summary>
    /// 属性17
    /// </summary>
    public readonly int MoveSpeed;
    /// <summary>
    /// 属性18
    /// </summary>
    public readonly int PhysicsBloodsuckingR;
    /// <summary>
    /// 属性19
    /// </summary>
    public readonly int MagicBloodsuckingR;
    /// <summary>
    /// 属性20
    /// </summary>
    public readonly int AttackRange;
    /// <summary>
    /// 属性21
    /// </summary>
    public readonly int PerSecondBloodR;
    /// <summary>
    /// 属性22
    /// </summary>
    public readonly int PerSecondManaR;
    /// <summary>
    /// 属性23
    /// </summary>
    public readonly int ResilienceR;


    public const int __ID__ = 1407018283;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Code:" + Code + ","
        + "Name:" + Name + ","
        + "UpgradeCode:" + UpgradeCode + ","
        + "ActiveSkills:" + Luban.StringUtil.CollectionToString(ActiveSkills) + ","
        + "PassiveSkills:" + Luban.StringUtil.CollectionToString(PassiveSkills) + ","
        + "Hp:" + Hp + ","
        + "MaxHp:" + MaxHp + ","
        + "ExtraHp:" + ExtraHp + ","
        + "PhysicsAttack:" + PhysicsAttack + ","
        + "MagicAttack:" + MagicAttack + ","
        + "ExtraPhysicsAttack:" + ExtraPhysicsAttack + ","
        + "ExtraMagicAttack:" + ExtraMagicAttack + ","
        + "PhysicsDefense:" + PhysicsDefense + ","
        + "MagicDefense:" + MagicDefense + ","
        + "Mana:" + Mana + ","
        + "MaxMana:" + MaxMana + ","
        + "CriticalR:" + CriticalR + ","
        + "AttackSpeedR:" + AttackSpeedR + ","
        + "CooldownReduceR:" + CooldownReduceR + ","
        + "PhysicsPenetrationR:" + PhysicsPenetrationR + ","
        + "MagicPenetrationR:" + MagicPenetrationR + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "PhysicsBloodsuckingR:" + PhysicsBloodsuckingR + ","
        + "MagicBloodsuckingR:" + MagicBloodsuckingR + ","
        + "AttackRange:" + AttackRange + ","
        + "PerSecondBloodR:" + PerSecondBloodR + ","
        + "PerSecondManaR:" + PerSecondManaR + ","
        + "ResilienceR:" + ResilienceR + ","
        + "}";
    }
}
}

