
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class DRBuff : Luban.BeanBase
{
    public DRBuff(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        Name = (string)_obj.GetValue("Name");
        DurationMs = (int)_obj.GetValue("DurationMs");
        OngoingEffectId = (int)_obj.GetValue("OngoingEffectId");
        { var __json0 = _obj.GetValue("OnAddEffects"); OnAddEffects = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  OnAddEffects.Add(__v0); }   }
        { var __json0 = _obj.GetValue("OnRemoveEffects"); OnRemoveEffects = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  OnRemoveEffects.Add(__v0); }   }
        { var __json0 = _obj.GetValue("OnIntervalEffects"); OnIntervalEffects = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  OnIntervalEffects.Add(__v0); }   }
        IntervalMs = (int)_obj.GetValue("IntervalMs");
        StackingPolicy = (int)_obj.GetValue("StackingPolicy");
        RefreshPolicy = (int)_obj.GetValue("RefreshPolicy");
        MaxStacks = (int)_obj.GetValue("MaxStacks");
        { var __json0 = _obj.GetValue("TriggerIds"); TriggerIds = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  TriggerIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("Tags"); Tags = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  Tags.Add(__v0); }   }
    }

    public static DRBuff DeserializeDRBuff(JToken _buf)
    {
        return new DRBuff(_buf);
    }

    /// <summary>
    /// 属性编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 持续毫秒
    /// </summary>
    public readonly int DurationMs;
    /// <summary>
    /// 持续生效效果id
    /// </summary>
    public readonly int OngoingEffectId;
    /// <summary>
    /// 添加时效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> OnAddEffects;
    /// <summary>
    /// 移除时效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> OnRemoveEffects;
    /// <summary>
    /// 间隔触发效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> OnIntervalEffects;
    /// <summary>
    /// 间隔毫秒
    /// </summary>
    public readonly int IntervalMs;
    /// <summary>
    /// 叠加方式
    /// </summary>
    public readonly int StackingPolicy;
    /// <summary>
    /// 刷新方式
    /// </summary>
    public readonly int RefreshPolicy;
    /// <summary>
    /// 最大层数
    /// </summary>
    public readonly int MaxStacks;
    /// <summary>
    /// 监听效果列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> TriggerIds;
    /// <summary>
    /// 标签列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Tags;


    public const int __ID__ = 2024592897;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "DurationMs:" + DurationMs + ","
        + "OngoingEffectId:" + OngoingEffectId + ","
        + "OnAddEffects:" + Luban.StringUtil.CollectionToString(OnAddEffects) + ","
        + "OnRemoveEffects:" + Luban.StringUtil.CollectionToString(OnRemoveEffects) + ","
        + "OnIntervalEffects:" + Luban.StringUtil.CollectionToString(OnIntervalEffects) + ","
        + "IntervalMs:" + IntervalMs + ","
        + "StackingPolicy:" + StackingPolicy + ","
        + "RefreshPolicy:" + RefreshPolicy + ","
        + "MaxStacks:" + MaxStacks + ","
        + "TriggerIds:" + Luban.StringUtil.CollectionToString(TriggerIds) + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "}";
    }
}
}

