
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class DRCharacters : Luban.BeanBase
{
    public DRCharacters(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Code = (int)_obj.GetValue("Code");
        Name = (string)_obj.GetValue("Name");
        { var __json0 = _obj.GetValue("Career"); Career = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  Career.Add(__v0); }   }
        ModelId = (int)_obj.GetValue("ModelId");
        AttributeTemplateId = (int)_obj.GetValue("AttributeTemplateId");
    }

    public static DRCharacters DeserializeDRCharacters(JToken _buf)
    {
        return new DRCharacters(_buf);
    }

    /// <summary>
    /// 角色编号
    /// </summary>
    public readonly int Code;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 职业
    /// </summary>
    public readonly System.Collections.Generic.List<int> Career;
    /// <summary>
    /// 模型Id
    /// </summary>
    public readonly int ModelId;
    /// <summary>
    /// 战斗模板Id
    /// </summary>
    public readonly int AttributeTemplateId;


    public const int __ID__ = 2105456024;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Code:" + Code + ","
        + "Name:" + Name + ","
        + "Career:" + Luban.StringUtil.CollectionToString(Career) + ","
        + "ModelId:" + ModelId + ","
        + "AttributeTemplateId:" + AttributeTemplateId + ","
        + "}";
    }
}
}

